### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by Kelby2** [Kelby2/pixelgram#8]

**Comment by mashuDuek** [comment]
Hey Kelby, 

Looks great! The error handling looks good. And the styling of both components looks good. 

I was under the impression that login and signup occurred both in "/" route. That we didn't need frontend routes "/login" and "/signup". Let me know why you decided to make these routes. 

Mashu 


I

**Comment by Kelby2** [comment]
Hey Mashu,
I changed the routes so we no longer have /login and /signup. Please review when you get a chance!
